Update shift-left-k8s-pipeline.yml

diff --git a/.github/workflows/shift-left-k8s-pipeline.yml b/.github/workflows/shift-left-k8s-pipeline.yml
--- a/.github/workflows/shift-left-k8s-pipeline.yml
+++ b/.github/workflows/shift-left-k8s-pipeline.yml
@@ -87,6 +87,29 @@ jobs:
           done
         shell: bash
 
+      - name: Run kube-bench for CIS Benchmark
+        run: |
+          docker run --rm --privileged \
+            -v /var/lib:/var/lib:ro \
+            -v /var/run/docker.sock:/var/run/docker.sock:ro \
+            -v /etc:/etc:ro \
+            -v /usr/bin:/host/usr/bin:ro \
+            -v /usr/lib:/host/usr/lib:ro \
+            -v /proc:/host/proc:ro \
+            -v /boot:/host/boot:ro \
+            -v /lib/modules:/host/lib/modules:ro \
+            aquasec/kube-bench:latest > kube-bench-report.json 2>&1 || true
+        shell: bash
+
+      - name: Scan YAML Manifests with kube-score (SAST)
+        run: |
+          mkdir -p kube-score-reports
+          find $(pwd)/kubernetes-goat/scenarios -type f -name '*.yaml' | while read -r file; do
+            base_name=$(basename "$file")
+            docker run --rm -v $(pwd)/kubernetes-goat/scenarios:/scenarios zegl/kube-score:latest score "/scenarios/$base_name" > "kube-score-reports/${base_name%.yaml}-score.txt" || echo "Skipping invalid file: $file"
+          done
+        shell: bash
+
 
       - name: Install Trivy
         run: |
